services:
  react:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    volumes:
      - react_static_files:/app/build
  nginx:
    image: nginx:alpine
    volumes:
      - "./nginx/prod/conf.d/:/etc/nginx/conf.d/:ro"
      - react_static_files:/usr/share/nginx/html

volumes:
  react_static_files:
    driver: local