services:
  react:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app
    command: yarn start
  nginx:
    volumes:
      - ./nginx/dev/default.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./local-certs/certs/:/etc/ssl/certs/
      - ./local-certs/private/:/etc/ssl/private/
    