version: '3.1'

services:
  flask:
    build:
      context: ./server
    depends_on:
      - postgres
    env_file:
      - .env
    command: gunicorn --bind 0.0.0.0:5000 --timeout 0 "app:app"

  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/:/docker-entrypoint-initdb.d/

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    depends_on:
      - react
      - flask
    env_file:
      - .env

volumes:
  postgres_data:
