version: '3.1'

services:
  react:
    build:
      context: ./client
    volumes:
      - react_static_files:/app/build

  flask:
    build:
      context: ./server
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    env_file:
      - .env
    command: gunicorn --bind 0.0.0.0:5000 --timeout 0 "app:app"

  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    depends_on:
      - react
      - flask
    volumes:
      - react_static_files:/usr/share/nginx/html
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro

volumes:
  postgres_data:

  react_static_files:
    driver: local
