services:
  react:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app
    command: yarn start
  nginx:
    image: nginx:alpine
    ports:
      - 443:443
    volumes:
      - ./nginx/dev/conf.d/:/etc/nginx/conf.d/:ro
      - ./local-certs/certs/:/etc/ssl/certs/
      - ./local-certs/private/:/etc/ssl/private/
    